### PR TITLE
Fix #142

### LINKED ISSUE #142: SAML Frontend always return NameID with format persistent
Function 

``` python
def hash_type_to_saml_name_id_format(hash_type):
    """
    Translate satosa format to pySAML2 name format

    :type hash_type: satosa.internal_data.UserIdHashType
    :rtype: str
    :param hash_type: satosa format
    :return: pySAML2 name format
    """
    if hash_type == UserIdHashType.transient.name:
        return NAMEID_FORMAT_TRANSIENT
    elif hash_type == UserIdHashType.persistent.name:
        return NAMEID_FORMAT_PERSISTENT
    return NAMEID_FORMAT_PERSISTENT

```

in https://github.com/SUNET/SATOSA/blob/master/src/satosa/frontends/saml2.py#L31

compares `hash_type` which is a UserIdHashType object to ` UserIdHashType.transient.name` which is a string. This comparison is always False, hence the default return is always followed and the SAML2 frontent always creates an assertion with NameID format persistent in the Subject.

### PR DESCRIPTION
**Pull request by jkakavas**
Make sure we compare same types

### CODE REVIEW

**Comment by jkakavas** [comment]
Changed this to compare by identity, as suggested in https://docs.python.org/3/library/enum.html#comparisons

**Comment by johanlundberg** [comment]
Should I merge this or wait for #137?

**Comment by jkakavas** [comment]
Not sure, to be honest... I think #137 might take some more time and this is a quite significant bug (not being able to release a transient NameID ) so I say merge this and rewrite #137 based on this

**Comment by johanlundberg** [comment]
Sounds good to me.

**Pull request merged**
